spring.application.name=backend

spring.datasource.url=jdbc:postgresql://ep-steep-lab-anhnm7th-pooler.c-6.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_utP4VizOab6m&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_utP4VizOab6m
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=true